apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stg
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argo
    name: in-cluster
  project: stg
  source:
    path: apps
    repoURL: https://github.com/ayalaluquez/argocd-example-apps
    targetRevision: HEAD
