apiVersion: v1
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: argocd
    meta.helm.sh/release-namespace: argocd
  labels:
    app.kubernetes.io/managed-by: Helm
    argocd.argoproj.io/secret-type: cluster
    env: prd
  name: prd-cluster
  namespace: argocd
data:
  name: Z2l0b3BzCg==
  server: aHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjCg==
type: Opaque