apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: '{{name}}-appset'
    spec:
      project: default
      source:
        repoURL: https://github.com/ayalaluquez/argocd-example-apps.git
        targetRevision: HEAD
        path: helm-chart
      destination:
        name: "{{server}}"
        namespace: appset
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true