apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset
spec:
  generators:
    - list:
        elements:
          - cluster: stg
            url: https://kubernetes.default.svc
          - cluster: prd
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-app-set'
    spec:
      project: default
      source:
        repoURL: {{ .Values.spec.source.repoURL }}
        targetRevision: {{ .Values.spec.source.targetRevision }}
        path: helm-chart
      destination:
        server: '{{url}}'
        namespace: appset