apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ucc
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ucc
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.destination.enviroment }}
  source:
    path: helm-chart
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}

